Project_Petrol_Pump/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import home
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home',home,name="home-page"),
    path("",LoginView.as_view(template_name='users/login.html'),name="login"),
    path("logout",LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path("rates/",include("rates.urls")),
    path("nozzel/", include("nozzel.urls")),
    path("employee/", include("employee.urls")),
    path("tank/", include("tank.urls")),
    path("creditor/", include("creditor.urls")),
    path("vehicle/", include("vehicle.urls"))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tank/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/",NewTankView.as_view(),name="Tank-new"),
    path("view/",ListTankView.as_view(),name="Tank-view"),
    path("update/<int:pk>",UpdateTankView.as_view(),name="Tank-update"),
    path("delete/<int:pk>",DeleteTankView.as_view(),name="Tank-delete")
]

tank/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class tank_master(models.Model):
    date=models.DateField()
    petrolbefore=models.FloatField()
    dieselbefore=models.FloatField()
    petrolafter = models.FloatField(null=True,blank=True)
    dieselafter = models.FloatField(null=True,blank=True)
    lostpetrol = models.FloatField(null=True,blank=True)
    lostdiesel = models.FloatField(null=True,blank=True)
    lostpetrolprice = models.FloatField(null=True,blank=True)
    lostdieselprice = models.FloatField(null=True,blank=True)

    def __str__(self):
        return f"petrol({self.lostpetrol})-diesel({self.lostdiesel})"

    def get_absolute_url(self):
        return reverse('Tank-view')

tank/views.py
from django.shortcuts import render
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,DetailView
from .models import tank_master
# Create your views here.
class NewTankView(CreateView):
    model = tank_master
    fields = '__all__'

#model_form.html

class ListTankView(ListView):
    model = tank_master
    context_object_name = 'tank_masters'
#model_list.html
class UpdateTankView(UpdateView):
    model = tank_master
    fields = '__all__'

class DeleteTankView(DeleteView):
    model = tank_master
    success_url = '/tank_masters/view'
#model_confirm_delete.html
class DetailTankView(DetailView):
    model = tank_master

tank/templates/tank/tank_master_confirm_delete.html
{% extends "user/layout.html" %}
{% block body %}
    <h1> Are you sure you want to delete ?</h1>
    <form method="post">
    {% csrf_token %}
     <ul>
        <li> Date : {{ object.date }}</li>
        <li> Petrol Before :{{ object.petrolbefore }}</li>
        <li> Petrol After :{{ object.petrolafter }}</li>
        <li> Petrol lost in liters :{{ object.lostpetrol }}</li>
        <li> Petrol Lost in price :{{ object.lostpetrolprice }}</li>
        <li> Diesel Before : {{ object.dieselbefore }}</li>
        <li> Diesel After : {{ object.dieselafter }}</li>
        <li> Diesel lost in liters :{{ object.lostdiesel }}</li>
        <li> Diesel lost in price :{{ object.lostdieselprice }}</li>
     </ul>
        <input type="submit" value="delete" class="btn btn-danger">
        <a href="{% url 'rate-view' %}" class="btn btn-info" >cancel </a>
    </form>
{% endblock %}

tank/templates/tank/tank_master_form.html
{% extends "users/layout.html" %}
{% load static %}
{% load crispy_forms_field %}
{% block extra_css %}
    <!-- Animation Css -->
    <link href="{% static 'plugins/animate-css/animate.css'%}" rel="stylesheet" />

    <!-- Sweet Alert Css -->
    <link href="{% static 'plugins/sweetalert/sweetalert.css'%}" rel="stylesheet" />

      <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css'%}" rel="stylesheet" />

    <!-- Bootstrap DatePicker Css -->
    <link href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css'%}" rel="stylesheet" />


{% endblock %}
{% block body %}
{#    <div class="block-header">#}
{#                <h2>#}
{#                    FORM VALIDATION#}
{#                    <small>Taken from <a href="https://jqueryvalidation.org/" target="_blank">jqueryvalidation.org</a></small>#}
{#                </h2>#}
{#            </div>#}
            <!-- Basic Validation -->
                        <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Rate Entry Form</h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <form id="form_validation" method="POST">
                                {% csrf_token %}
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.date 'class' 'datepicker' %}
                                        <label class="form-label">Date </label>
                                         {% if form.date.errors %}
                                            {% for error in form.date.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.petrolbefore %}
                                        <label class="form-label">Petrol Before in liters</label>
                                         {% if form.petrolbefore.errors %}
                                            {% for error in form.petrolbefore.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.dieselbefore %}
                                        <label class="form-label">Diesel Before in liters</label>
                                        {% if form.dieselbefore.errors %}
                                            {% for error in form.dieselbefore.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                              <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.petrolafter %}
                                        <label class="form-label">Petrol After In Liters</label>
                                        {% if form.petrolafter.errors %}
                                            {% for error in form.petrolafter.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.dieselafter %}
                                        <label class="form-label">Diesel After In Liters</label>
                                        {% if form.dieselafter.errors %}
                                            {% for error in form.dieselafter.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.lostpetrol %}
                                        <label class="form-label">Lost Petrol in liters</label>
                                        {% if form.lostpetrol.errors %}
                                            {% for error in form.lostpetrol.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.lostdiesel %}
                                        <label class="form-label">Lost Diesel in liters</label>
                                        {% if form.lostdiesel.errors %}
                                            {% for error in form.lostdiesel.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.lostpetrolprice %}
                                        <label class="form-label">Lost petrol price</label>
                                        {% if form.lostpetrolprice.errors %}
                                            {% for error in form.lostpetrolprice.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {% crispy_field form.lostdieselprice %}
                                        <label class="form-label">Lost diesel price</label>
                                        {% if form.lostdieselprice.errors %}
                                            {% for error in form.lostdieselprice.errors %}
                                                <div class="invalid-feedback">
                                                  {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>

                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Validation -->
{% endblock %}
{% block extra_js %}
     <!-- Jquery Validation Plugin Css -->
    <script src="{% static 'plugins/jquery-validation/jquery.validate.js'%}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{% static 'plugins/jquery-steps/jquery.steps.js'%}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{% static 'plugins/sweetalert/sweetalert.min.js'%}"></script>

    <script src="{% static 'js/pages/forms/form-validation.js'%}"></script>

     <!-- Moment Plugin Js -->
    <script src="{% static 'plugins/momentjs/moment.js'%}"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{%  static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js'%}"></script>

    <!-- Bootstrap Datepicker Plugin Js -->
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'%}"></script>
    <script>
         $('.datepicker').bootstrapMaterialDatePicker({
        format: 'YYYY-MM-DD',
        clearButton: true,
        weekStart: 1,
        time: false
    });

    </script>

    <script>
      document.addEventListener('DOMContentLoaded',function(){

          //document.querySelector("button").on
          document.querySelector("#id_lostpetrol").onkeyup=function(){

              // fetch the rate of petrol
              fetch("http://127.0.0.1:8000/rates/petrolprice/")
              .then(response => response.json())
              .then(data => {

                  console.log(data.petrol_price);  //50
                  let lostpp=document.querySelector("#id_lostpetrolprice");
                  lostpp.value=data.petrol_price*this.value;

              })
          }


      })
    </script>

{% endblock %}

tank/templates/tank/tank_master_list.html
{% extends "user/layout.html" %}
{% load static %}
{% block extra_css %}
     <!-- JQuery DataTable Css -->
    <link href="{% static 'plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css'%}" rel="stylesheet">

{% endblock %}
{% block body %}
               <!-- Exportable Table -->
 <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Rate  TABLE
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Petrol before in liters</th>
                                            <th>Petrol after in liters</th>
                                            <th>lost petrol in liters</th>
                                            <th>Lost petrol price</th>
                                            <th>Diesel before in liters</th>
                                            <th>Diesel after in liters</th>
                                            <th>lost diesel in liters</th>
                                            <th>Lost diesel price</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Date</th>
                                            <th>Petrol before in liters</th>
                                            <th>Petrol after in liters</th>
                                            <th>lost petrol in liters</th>
                                            <th>Lost petrol price</th>
                                            <th>Diesel before in liters</th>
                                            <th>Diesel after in liters</th>
                                            <th>lost diesel in liters</th>
                                            <th>Lost diesel price</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                   <tbody>
                                   {% for value in tank_masters %}
                                       <tr>
                                        <td>{{ value.date }}</td>
                                        <td>{{ value.petrolbefore }}</td>
                                        <td>{{ value.petrolafter }}</td>
                                        <td>{{ value.lostpetrol }}</td>
                                        <td>{{ value.lostpetrolprice }}</td>
                                        <td>{{ value.dieselbefore }}</td>
                                        <td>{{ value.dieselafter }}</td>
                                        <td>{{ value.lostdiesel }}</td>
                                        <td>{{ value.lostdieselprice }}</td>

                                       <th>
                                           <a href="{% url 'Tank-update'  value.id %}" class="btn btn-info"> update</a>
                                           <a href="{% url 'Tank-delete'  value.id %}" class="btn btn-danger"> Delete</a>
                                       </th>

                                       </tr>
                                   {% endfor %}
                                   </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
{% endblock %}
{% block extra_js %}
      <!-- Jquery DataTable Plugin Js -->
    <script src="{% static 'plugins/jquery-datatable/jquery.dataTables.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.flash.min.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/jszip.min.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/pdfmake.min.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/vfs_fonts.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.html5.min.js'%}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.print.min.js'%}"></script>

    <!-- Custom Js -->
    <script src="{% static 'js/admin.js'%}"></script>
    <script src="{% static 'js/pages/tables/jquery-datatable.js'%}"></script>

{% endblock %}